version: "2"
services:
  goon_waitlist:
    container_name: waitlist
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUID: ${PUID}
        PGID: ${PGID}
    command: npm run start
    volumes:
      - .:/opt/goon_waitlist/
      - /opt/goon_waitlist/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGODB_URL: mongodb://mongo
  mongo:
    container_name: mongo
    image: mvertes/alpine-mongo
    volumes:
      - /data/db:/data/db
    ports:
      - "27017:27017"
